### ISSUE TITLE
Recommended change to the usage docs

### ISSUE THREAD

**Issue by erikeckhardt** [lukewarlow/user-agent-data-types#3]
Your npm package docs say to do this in `tsconfig.json`:

```
{
  "compilerOptions": {
    "types": [
        "./node_modules/user-agent-data-types"
    ]
  }
}
```

That is against best practice and a bit unfriendly, because as soon the `types` or `typeRoots` keys are present in `tsconfig.json`, that excludes all other type usage in the entire project.

The friendly way to expose ambient types from another project involves:

1. <strike>Wrap your `index.d.ts` content in a `declare global { }` block.</strike> // this isn't necessary, actually
2. Have your consumers create a file with a `.d.ts` extension in their own project, inside of their source code covered by their tsconfig.json, for example `src/user-agent-data-types.d.ts`:
    ```typescript
    /// <reference types="user-agent-data-types" />
    ```

Boom. Ambient types available in consumer projects, no excluding all other types from their entire type resolution pool.

**Comment by lukewarlow** [comment]
Thanks for letting me know that! I kind of guessed how to do it on another package.

Happy to accept a PR that does this 👍.
Else it may be a bit before I get round to this.

**Comment by erikeckhardt** [comment]
It turns out that you don't even need to add the `declare global {}`. I'll submit a PR.

**Comment by erikeckhardt** [comment]
@lukewarlow Opened a PR for you! I hope you like it. Feel free to ask for something different.

I've tested this in a project using the triple-slash directive and it does work correctly.

**Comment by lukewarlow** [comment]
Great thanks. I will take a look tomorrow!
