### ISSUE TITLE
navigator.userAgentData in firefox

### ISSUE THREAD

**Issue by Faegen** [lukewarlow/user-agent-data-types#6]
Hello 

I use the npm package with  navigator.userAgentData.getHighEntropyValues([“platformVersion”])

This also works great.
Only in Firefox navigator.userAgent is undefined and the whole thing does not work.

Is there a solution for this

**Comment by lukewarlow** [comment]
Firefox doesn't implement this API and so navigator.userAgentData will be undefined. There may be polyfill packages available but this is just for the typescript types.
